name: context_builder
description: A Flutter widget library that combines platform, orientation, and screen-size-relative scaling utilities into one widget.
version: 0.0.1
author: Andrew Ackerman <andrew.ackie@gmail.com>
homepage: https://github.com/andrewackerman/context_builder

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: